spring:
  profiles:
    active: local
server:
  port: 8088

---
spring:
  profiles: local

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      test-service:
        registerHealthIndicator: true
        failureRateThreshold: 50 # Expected percentage of the failure threshold yüzde 50 e?i?i
        minimumNumberOfCalls: 10  # Minimum number of total API calls to decide failure percentage to enable the breaker. 10 cagr?dan 6 s? hata verir ise circuit-breaker ac?l?r
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s # Timeout period before going to HALF OPEN state from OPEN state. After 5 seconds, breaker will change the state, here.
        permittedNumberOfCallsInHalfOpenState: 3 # yar? ac?k durumdayken 3 cagr?da yeniden hata al?rsa ac?k duruma gecer.
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED